[package]
name = "src-qa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.30"
langchain-rust = { version = "4.0.3", features = ["tree-sitter"] }
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["full"] }
